2021-11-21 22:11:58,442 INFO    MainThread:80766 [internal.py:wandb_internal():87] W&B internal server running at pid: 80766, started at: 2021-11-21 22:11:58.442218
2021-11-21 22:11:58,445 DEBUG   HandlerThread:80766 [handler.py:handle_request():130] handle_request: check_version
2021-11-21 22:11:58,445 INFO    WriterThread:80766 [datastore.py:open_for_write():77] open: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/run-2bij56y6.wandb
2021-11-21 22:11:58,448 DEBUG   SenderThread:80766 [sender.py:send():238] send: header
2021-11-21 22:11:58,448 DEBUG   SenderThread:80766 [sender.py:send_request():252] send_request: check_version
2021-11-21 22:11:59,437 DEBUG   SenderThread:80766 [sender.py:send():238] send: run
2021-11-21 22:11:59,954 INFO    SenderThread:80766 [dir_watcher.py:__init__():169] watching files in: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files
2021-11-21 22:11:59,954 INFO    SenderThread:80766 [sender.py:_start_run_threads():825] run started: 2bij56y6 with start time 1637503917
2021-11-21 22:11:59,954 DEBUG   SenderThread:80766 [sender.py:send():238] send: summary
2021-11-21 22:11:59,954 INFO    SenderThread:80766 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2021-11-21 22:11:59,955 DEBUG   HandlerThread:80766 [handler.py:handle_request():130] handle_request: run_start
2021-11-21 22:11:59,960 DEBUG   HandlerThread:80766 [meta.py:__init__():40] meta init
2021-11-21 22:11:59,961 DEBUG   HandlerThread:80766 [meta.py:__init__():54] meta init done
2021-11-21 22:11:59,961 DEBUG   HandlerThread:80766 [meta.py:probe():214] probe
2021-11-21 22:11:59,967 DEBUG   HandlerThread:80766 [meta.py:_setup_git():204] setup git
2021-11-21 22:11:59,987 DEBUG   HandlerThread:80766 [meta.py:_setup_git():211] setup git done
2021-11-21 22:11:59,987 DEBUG   HandlerThread:80766 [meta.py:_save_pip():58] save pip
2021-11-21 22:11:59,988 DEBUG   HandlerThread:80766 [meta.py:_save_pip():72] save pip done
2021-11-21 22:11:59,989 DEBUG   HandlerThread:80766 [meta.py:probe():252] probe done
2021-11-21 22:11:59,994 DEBUG   SenderThread:80766 [sender.py:send():238] send: files
2021-11-21 22:11:59,995 INFO    SenderThread:80766 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2021-11-21 22:12:00,004 DEBUG   HandlerThread:80766 [handler.py:handle_request():130] handle_request: stop_status
2021-11-21 22:12:00,005 DEBUG   SenderThread:80766 [sender.py:send_request():252] send_request: stop_status
2021-11-21 22:12:00,487 DEBUG   SenderThread:80766 [sender.py:send():238] send: config
2021-11-21 22:12:00,488 DEBUG   SenderThread:80766 [sender.py:send():238] send: metric
2021-11-21 22:12:00,488 DEBUG   SenderThread:80766 [sender.py:send():238] send: metric
2021-11-21 22:12:00,957 INFO    Thread-8  :80766 [dir_watcher.py:_on_file_created():217] file/dir created: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files/output.log
2021-11-21 22:12:00,958 INFO    Thread-8  :80766 [dir_watcher.py:_on_file_created():217] file/dir created: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files/requirements.txt
2021-11-21 22:12:00,958 INFO    Thread-8  :80766 [dir_watcher.py:_on_file_created():217] file/dir created: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files/wandb-metadata.json
2021-11-21 22:12:00,958 INFO    Thread-8  :80766 [dir_watcher.py:_on_file_created():217] file/dir created: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files/wandb-summary.json
2021-11-21 22:12:00,984 INFO    Thread-11 :80766 [upload_job.py:push():137] Uploaded file /tmp/tmpl7ridf7wwandb/36o10tfw-wandb-metadata.json
2021-11-21 22:12:02,956 INFO    Thread-8  :80766 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files/output.log
2021-11-21 22:12:15,511 DEBUG   HandlerThread:80766 [handler.py:handle_request():130] handle_request: stop_status
2021-11-21 22:12:15,511 DEBUG   SenderThread:80766 [sender.py:send_request():252] send_request: stop_status
2021-11-21 22:12:26,974 INFO    Thread-8  :80766 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files/output.log
2021-11-21 22:12:28,409 DEBUG   SenderThread:80766 [sender.py:send():238] send: stats
2021-11-21 22:12:28,975 INFO    Thread-8  :80766 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files/output.log
2021-11-21 22:12:29,280 ERROR   SenderThread:80766 [internal_api.py:execute():144] 409 response executing GraphQL.
2021-11-21 22:12:29,280 ERROR   SenderThread:80766 [internal_api.py:execute():145] {"errors":[{"message":"Error 1062: Duplicate entry '557039-2bij56y6' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-11-21 22:12:29,781 INFO    HandlerThread:80766 [handler.py:finish():731] shutting down handler
2021-11-21 22:12:29,791 INFO    WriterThread:80766 [datastore.py:close():281] close: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/run-2bij56y6.wandb
2021-11-21 22:12:29,792 ERROR   MainThread:80766 [internal.py:wandb_internal():158] Thread SenderThread:
Traceback (most recent call last):
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1298, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 52, in run
    self._run()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 96, in _run
    self._debounce()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 297, in _debounce
    self._sm.debounce()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 319, in debounce
    self._debounce_config()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 325, in _debounce_config
    self._api.upsert_run(
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
2021-11-21 22:12:30,977 INFO    Thread-8  :80766 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/yu-jw19/venom/project2/wandb/run-20211121_221157-2bij56y6/files/output.log
2021-11-21 22:12:31,814 INFO    MainThread:80766 [internal.py:handle_exit():77] Internal process exited
